blank_issues_enabled: false
contact_links:
  - name: 🆘 Hibaelhárítás
    url: https://github.com/MultiUploader/MultiUploader.github.io#-hibaelhárítás
    about: Gyakori problémák (Auth Test piros, TMDB hiba, nincs mintakép…) és megoldásuk.
